### PR TITLE
Cast table node exceptions into ParserExceptions when throwing

### LINKED ISSUE #212: Inconsistent cells count throws low-level error
If we have a table that isn't rectangular:

```
| foo |
| bar | baz |
```

we get a specific exception that is not a ParserException - it should probably be caught and a ParserException thrown

Removing this line will produce a failing test
https://github.com/Behat/Gherkin/blob/master/tests/Behat/Gherkin/Cucumber/CompatibilityTest.php#L46

### PR DESCRIPTION
**Pull request by ciaranmcnulty**
Rather than leaking this, we should make a ParserException

Closes #212

### CODE REVIEW

File: src/Behat/Gherkin/Parser.php [hunk 1]
```diff
@@ -565,7 +566,16 @@ protected function parseExamples()
      */
     protected function parseTable()
     {
-        return new TableNode($this->parseTableRows());
+        try {
+            return new TableNode($this->parseTableRows());
+        }
+        catch(NodeException $e) {
```
Comment (stof) [inline src/Behat/Gherkin/Parser.php:572]: should be on the previous line to follow PSR-2/PSR-12

File: src/Behat/Gherkin/Parser.php [hunk 2]
```diff
@@ -565,7 +566,16 @@ protected function parseExamples()
...
+            throw new ParserException(
+                $e->getMessage() . $this->file ? ' in file '.$this->file : '',
```
Comment (stof) [inline src/Behat/Gherkin/Parser.php:574]: you are missing braces around the ternary. The current code is executed as `($e->getMessage() . $this->file) ? ' in file '.$this->file : ''` which is not what you want.

File: src/Behat/Gherkin/Parser.php [hunk 3]
```diff
@@ -565,7 +566,16 @@ protected function parseExamples()
      */
     protected function parseTable()
     {
-        return new TableNode($this->parseTableRows());
+        try {
+            return new TableNode($this->parseTableRows());
```
Comment (stof) [inline src/Behat/Gherkin/Parser.php:570]: I would probably keep the `parseTableRows` outside the `try/catch` so that we catch only the exceptions from `TableNode`.

**Review by stof — CHANGES_REQUESTED** [review]
We probably need the same try/catch in `parseExamples` when instantiating the `ExampleTableNode`

**Review by stof — APPROVED** [review]
